config/routes.rb
Rails.application.routes.draw do
  resources :mineral_calculations
  resources :calculations
  resources :minerals
  resources :alien_numerals
  resources :roman_numerals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#dashboard"
end

app/models/mineral_calculation.rb
class MineralCalculation < ApplicationRecord
end

app/controllers/mineral_calculations_controller.rb
class MineralCalculationsController < ApplicationController
  before_action :set_mineral_calculation, only: [:show, :edit, :update, :destroy]

  # GET /mineral_calculations
  # GET /mineral_calculations.json
  def index
    @mineral_calculations = MineralCalculation.all
  end

  # GET /mineral_calculations/1
  # GET /mineral_calculations/1.json
  def show
  end

  # GET /mineral_calculations/new
  def new
    @mineral_calculation = MineralCalculation.new
    @alien_numerals = AlienNumeral.all
    @minerals = Mineral.all
  end

  # GET /mineral_calculations/1/edit
  def edit
  end

  # POST /mineral_calculations
  # POST /mineral_calculations.json
  def create
    @mineral_calculation = MineralCalculation.new(mineral_calculation_params)

    respond_to do |format|
      if @mineral_calculation.save
        format.html { redirect_to root_path, notice: 'Mineral calculation was successfully created.' }
        format.json { render :show, status: :created, location: @mineral_calculation }
      else
        format.html { render :new }
        format.json { render json: @mineral_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mineral_calculations/1
  # PATCH/PUT /mineral_calculations/1.json
  def update
    respond_to do |format|
      if @mineral_calculation.update(mineral_calculation_params)
        format.html { redirect_to @mineral_calculation, notice: 'Mineral calculation was successfully updated.' }
        format.json { render :show, status: :ok, location: @mineral_calculation }
      else
        format.html { render :edit }
        format.json { render json: @mineral_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mineral_calculations/1
  # DELETE /mineral_calculations/1.json
  def destroy
    @mineral_calculation.destroy
    respond_to do |format|
      format.html { redirect_to mineral_calculations_url, notice: 'Mineral calculation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mineral_calculation
      @mineral_calculation = MineralCalculation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mineral_calculation_params
      params.require(:mineral_calculation).permit(:alien_one, :alien_one_name, :alien_two, :alien_two_name, :mineral, :mineral_name, :total_value)
    end
end

app/helpers/mineral_calculations_helper.rb
module MineralCalculationsHelper
end

app/views/mineral_calculations/_form.html.erb
<%= form_for(mineral_calculation) do |f| %>
  <% if mineral_calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mineral_calculation.errors.count, "error") %> prohibited this mineral_calculation from being saved:</h2>

      <ul>
      <% mineral_calculation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% alienoptions = options_from_collection_for_select(@alien_numerals, 'alien', 'alien') %>
    <% mineraloptions = options_from_collection_for_select(@minerals, 'name', 'name') %>

    How many Credits is
    <%= f.select :alien_one_name, alienoptions %> <%= f.select :alien_two_name, alienoptions %> <%= f.select :mineral_name, mineraloptions %>
    ?
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mineral_calculations/edit.html.erb
<h1>Editing Mineral Calculation</h1>

<%= render 'form', mineral_calculation: @mineral_calculation %>

<%= link_to 'Show', @mineral_calculation %> |
<%= link_to 'Back', mineral_calculations_path %>

app/views/mineral_calculations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mineral Calculations</h1>

<table>
  <thead>
    <tr>
      <th>Alien one</th>
      <th>Alien one name</th>
      <th>Alien two</th>
      <th>Alien two name</th>
      <th>Mineral</th>
      <th>Mineral name</th>
      <th>Total value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mineral_calculations.each do |mineral_calculation| %>
      <tr>
        <td><%= mineral_calculation.alien_one %></td>
        <td><%= mineral_calculation.alien_one_name %></td>
        <td><%= mineral_calculation.alien_two %></td>
        <td><%= mineral_calculation.alien_two_name %></td>
        <td><%= mineral_calculation.mineral %></td>
        <td><%= mineral_calculation.mineral_name %></td>
        <td><%= mineral_calculation.total_value %></td>
        <td><%= link_to 'Show', mineral_calculation %></td>
        <td><%= link_to 'Edit', edit_mineral_calculation_path(mineral_calculation) %></td>
        <td><%= link_to 'Destroy', mineral_calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mineral Calculation', new_mineral_calculation_path %>

app/views/mineral_calculations/new.html.erb
<h1>New Mineral Calculation</h1>

<%= render 'form', mineral_calculation: @mineral_calculation %>

<%= link_to 'Back', root_path %>

app/views/mineral_calculations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alien one:</strong>
  <%= @mineral_calculation.alien_one %>
</p>

<p>
  <strong>Alien one name:</strong>
  <%= @mineral_calculation.alien_one_name %>
</p>

<p>
  <strong>Alien two:</strong>
  <%= @mineral_calculation.alien_two %>
</p>

<p>
  <strong>Alien two name:</strong>
  <%= @mineral_calculation.alien_two_name %>
</p>

<p>
  <strong>Mineral:</strong>
  <%= @mineral_calculation.mineral %>
</p>

<p>
  <strong>Mineral name:</strong>
  <%= @mineral_calculation.mineral_name %>
</p>

<p>
  <strong>Total value:</strong>
  <%= @mineral_calculation.total_value %>
</p>

<%= link_to 'Edit', edit_mineral_calculation_path(@mineral_calculation) %> |
<%= link_to 'Back', mineral_calculations_path %>