config/routes.rb
Rails.application.routes.draw do
  resources :mineral_calculations
  resources :calculations
  resources :minerals
  resources :alien_numerals
  resources :roman_numerals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#dashboard"
end

app/models/mineral.rb
class Mineral < ApplicationRecord
end

app/controllers/minerals_controller.rb
class MineralsController < ApplicationController
  before_action :set_mineral, only: [:show, :edit, :update, :destroy]

  # GET /minerals
  # GET /minerals.json
  def index
    @minerals = Mineral.all
  end

  # GET /minerals/1
  # GET /minerals/1.json
  def show
  end

  # GET /minerals/new
  def new
    @alien_numerals = AlienNumeral.all
    @mineral = Mineral.new
  end

  # GET /minerals/1/edit
  def edit
  end

  # POST /minerals
  # POST /minerals.json
  def create
    @mineral = Mineral.new(mineral_params)

    respond_to do |format|
      if @mineral.save
        format.html { redirect_to root_path, notice: 'Mineral was successfully created.' }
        format.json { render :show, status: :created, location: @mineral }
      else
        format.html { render :new }
        format.json { render json: @mineral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minerals/1
  # PATCH/PUT /minerals/1.json
  def update
    respond_to do |format|
      if @mineral.update(mineral_params)
        format.html { redirect_to @mineral, notice: 'Mineral was successfully updated.' }
        format.json { render :show, status: :ok, location: @mineral }
      else
        format.html { render :edit }
        format.json { render json: @mineral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minerals/1
  # DELETE /minerals/1.json
  def destroy
    @mineral.destroy
    respond_to do |format|
      format.html { redirect_to minerals_url, notice: 'Mineral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mineral
      @mineral = Mineral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mineral_params
      params.require(:mineral).permit(:name, :value, :alien_value_one, :alien_value_two, :total)
    end
end

app/helpers/minerals_helper.rb
module MineralsHelper
end

app/views/minerals/_form.html.erb
<%= form_for(mineral) do |f| %>
    <% if mineral.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(mineral.errors.count, "error") %> prohibited this mineral from being saved:</h2>

          <ul>
            <% mineral.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% options = options_from_collection_for_select(@alien_numerals, 'value', 'alien') %>
    <%= f.select :alien_value_one, options %> <%= f.select :alien_value_two, options %>
      <%= f.text_field :name, placeholder: "name of mineral" %>
      is
      <%= f.number_field :total, placeholder: "total" %>
      credits

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/minerals/edit.html.erb
<h1>Editing Mineral</h1>

<%= render 'form', mineral: @mineral %>

<%= link_to 'Show', @mineral %> |
<%= link_to 'Back', minerals_path %>

app/views/minerals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Minerals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Alien value one</th>
      <th>Alien value two</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minerals.each do |mineral| %>
      <tr>
        <td><%= mineral.name %></td>
        <td><%= mineral.value %></td>
        <td><%= mineral.alien_value_one %></td>
        <td><%= mineral.alien_value_two %></td>
        <td><%= mineral.total %></td>
        <td><%= link_to 'Show', mineral %></td>
        <td><%= link_to 'Edit', edit_mineral_path(mineral) %></td>
        <td><%= link_to 'Destroy', mineral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mineral', new_mineral_path %>

app/views/minerals/new.html.erb
<h1>New Mineral</h1>

<%= render 'form', mineral: @mineral %>

<%= link_to 'Back', root_path %>

app/views/minerals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mineral.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @mineral.value %>
</p>

<p>
  <strong>Alien value one:</strong>
  <%= @mineral.alien_value_one %>
</p>

<p>
  <strong>Alien value two:</strong>
  <%= @mineral.alien_value_two %>
</p>

<p>
  <strong>Total:</strong>
  <%= @mineral.total %>
</p>

<%= link_to 'Edit', edit_mineral_path(@mineral) %> |
<%= link_to 'Back', minerals_path %>