config/routes.rb
Rails.application.routes.draw do
  resources :mineral_calculations
  resources :calculations
  resources :minerals
  resources :alien_numerals
  resources :roman_numerals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#dashboard"
end

app/models/alien_numeral.rb
class AlienNumeral < ApplicationRecord
end

app/controllers/alien_numerals_controller.rb
class AlienNumeralsController < ApplicationController
  before_action :set_alien_numeral, only: [:show, :edit, :update, :destroy]

  # GET /alien_numerals
  # GET /alien_numerals.json
  def index
    @alien_numerals = AlienNumeral.all
  end

  # GET /alien_numerals/1
  # GET /alien_numerals/1.json
  def show
  end

  # GET /alien_numerals/new
  def new
    @roman_numerals = RomanNumeral.all
    @alien_numeral = AlienNumeral.new
  end

  # GET /alien_numerals/1/edit
  def edit
  end

  # POST /alien_numerals
  # POST /alien_numerals.json
  def create
    @roman_numerals = RomanNumeral.all
    @alien_numeral = AlienNumeral.new(alien_numeral_params)

    respond_to do |format|
      if @alien_numeral.save
        format.html { redirect_to root_path, notice: 'Alien numeral was successfully created.' }
        format.json { render :show, status: :created, location: @alien_numeral }
      else
        format.html { render :new }
        format.json { render json: @alien_numeral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alien_numerals/1
  # PATCH/PUT /alien_numerals/1.json
  def update
    respond_to do |format|
      if @alien_numeral.update(alien_numeral_params)
        format.html { redirect_to @alien_numeral, notice: 'Alien numeral was successfully updated.' }
        format.json { render :show, status: :ok, location: @alien_numeral }
      else
        format.html { render :edit }
        format.json { render json: @alien_numeral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alien_numerals/1
  # DELETE /alien_numerals/1.json
  def destroy
    @alien_numeral.destroy
    respond_to do |format|
      format.html { redirect_to alien_numerals_url, notice: 'Alien numeral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alien_numeral
      @alien_numeral = AlienNumeral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alien_numeral_params
      params.require(:alien_numeral).permit(:alien, :value)
    end
end

app/helpers/alien_numerals_helper.rb
module AlienNumeralsHelper
end

app/views/alien_numerals/_form.html.erb
<%= form_for(alien_numeral) do |f| %>
  <% if alien_numeral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alien_numeral.errors.count, "error") %> prohibited this alien_numeral from being saved:</h2>

      <ul>
      <% alien_numeral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alien %>
    <%= f.text_field :alien %>
  </div>
  is
  <div class="field">
    <%= f.label :value %>
    <% options = options_from_collection_for_select(@roman_numerals, 'value', 'numeral') %>
    <%= f.select :value, options %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alien_numerals/edit.html.erb
<h1>Editing Alien Numeral</h1>

<%= render 'form', alien_numeral: @alien_numeral %>

<%= link_to 'Show', @alien_numeral %> |
<%= link_to 'Back', alien_numerals_path %>

app/views/alien_numerals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alien Numerals</h1>

<table>
  <thead>
    <tr>
      <th>Alien</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alien_numerals.each do |alien_numeral| %>
      <tr>
        <td><%= alien_numeral.alien %></td>
        <td><%= alien_numeral.value %></td>
        <td><%= link_to 'Show', alien_numeral %></td>
        <td><%= link_to 'Edit', edit_alien_numeral_path(alien_numeral) %></td>
        <td><%= link_to 'Destroy', alien_numeral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alien Numeral', new_alien_numeral_path %>

app/views/alien_numerals/new.html.erb
<h1>New Alien Numeral</h1>

<%= render 'form', alien_numeral: @alien_numeral %>

<%= link_to 'Back', root_path %>

app/views/alien_numerals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alien:</strong>
  <%= @alien_numeral.alien %>
</p>

<p>
  <strong>Value:</strong>
  <%= @alien_numeral.value %>
</p>

<%= link_to 'Edit', edit_alien_numeral_path(@alien_numeral) %> |
<%= link_to 'Back', alien_numerals_path %>